### ISSUE TITLE
When mocking the SUT instead of a dependency, the signature matcher receives an extra argument and fails

### ISSUE THREAD

**Issue by dbucky** [dbucky/Mockify#7]
I created **test_mockSUT** to illustrate the problem:
```perl
sub test_mockSUT {
    my $self = shift;
    my $SubTestName = (caller(0))[3];

    my $injector = Test::Mockify::Injector->new('FakeModuleStaticInjection');
    $injector->spy('dependency')->when();

    warn FakeModuleStaticInjection->client();

    ok(WasCalled($injector->getVerifier(), 'dependency'), "$SubTestName - prove SUT can be mocked directly")
}

package FakeModuleStaticInjection;
sub dependency {
    my ($self, $arg) = @_;
    return "$arg dependency";
}
sub client {
    my $self = shift;
    return $self->dependency('client');
}
```
The test fails when `FakeModuleStaticInjection->client()` is invoked, with this message:
```
No matching found for stringstring -> $VAR1 = [
          'FakeModuleStaticInjection',
          'client'
        ];
```
This is not an issue when a dependent module is mocked, as the first argument is shifted off by the SUT before the dependent function is called with the remaining arguments. It may be argued that you shouldn't do this sort of thing, but it seems reasonable that you may want to test one function in a module that relies on another function in the same module. This is the scenario I am covering with the above test.

**Comment by dbucky** [comment]
**test_someSelectedMockifyFeatures** is affected by this too

**Comment by dbucky** [comment]
I can think of two solutions:
1. Require a flag when creating the injector that tells it the SUT is the module being mocked
2. Update the signature matching logic so that if it fails to match, it will try again after removing the first parameter

The first option is annoying because I would prefer not having to make that distinction. However, the second option could potentially match a signature erroneously in the normal usage of mocking the dependency and not the SUT, although that would definitely be a rare edge case.

**Comment by ChristianBreitkreutz** [comment]
> mocking the SUT instead of a dependency

This is generally a really bad idea. Never mock your SUT! I know i did this too ;-) but this will give you untrustworthy tests. You have always the risk of writing a test which is testing your own mock.
Since you writing test for this code you can also change this code. (If this is not your code you are not responsible for testing)
 With your improvement, you actually removed the last excuse to mock the SUT. It was needed to inject static Functions with wrapper method in the SUT in order to override this dependency. It could be an Idea to detect this somehow and to throw a error if a programmer tries to mock the SUT.

**Comment by ChristianBreitkreutz** [comment]
The new Injector should be never used Mocking Methods of packages where you can create an Instance of. (This is a Job for the standard Mockify) With other words, the package have a constructor (and the methods a $self). If you can create an instance of a dependency you must inject this instance into your SUT via Constructor or with some kind of set-Method. Use this injector only to inject static-function-imports into your SUT.
